name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Apt update
      run: sudo apt update
    - name: setup
      run: sudo apt install genisoimage nodejs qemu-utils nasm -y
    - name: Run test
      run: make test
