name: Automatic Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Glowman554/setup-nasm@v1
    - name: setup
      run: sudo apt install genisoimage
    - name: make
      run: make iso
