name: Automatic Release

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: setup
      run: sudo apt install genisoimage qemu-utils nasm -y
    - name: make
      run: make iso
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: cdrom.iso 
