
name: Website update

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Glowman554/setup-nasm@v1
    - name: make
      run: make
    - name: pack
      run: make pack
    - name: Setup git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Clone and patch website
      run: |
        git clone https://github.com/Glowman554/Glowman554.github.io.git
        cp pack/* Glowman554.github.io/downloads/.
        cd Glowman554.github.io
        git add *
        git commit -m "auto update"
        git push
        
        
